#!/usr/bin/env bash
set -e

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"<<-EOSQL
  CREATE ROLE kestra
    WITH LOGIN
         PASSWORD '$KESTRA_DB_PASSWORD'
         NOSUPERUSER
         INHERIT
         NOCREATEDB
         NOCREATEROLE
         NOREPLICATION;

  CREATE ROLE lakekeeper
    WITH LOGIN
         PASSWORD '$LAKEKEEPER_DB_PASSWORD'
         NOSUPERUSER
         INHERIT
         NOCREATEDB
         NOCREATEROLE
         NOREPLICATION;

  CREATE DATABASE kestra OWNER $KESTRA_DB_USER;
  CREATE DATABASE lakekeeper OWNER $LAKEKEEPER_DB_USER;

  GRANT ALL PRIVILEGES ON DATABASE kestra TO $KESTRA_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE lakekeeper TO $LAKEKEEPER_DB_USER;
EOSQL
